version: '3.8'

services:


# Backend PHP avec Nginx et PHP-FPM
  backend:
    build: ./backend
    container_name: Back
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=1025
    networks:
      - camagru-network
    depends_on:
      - postgres
      - mailhog



# Serveur Nginx pour le backend to Serve PHP-FPM Files 
  nginx:
    build:
      context: ./nginx
    container_name: Nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/php-fpm:/var/www/html/php-fpm 
    depends_on:
      - backend
      - php-fpm
    networks:
      - camagru-network


# PHP-FPM
  php-fpm:
    image: php:8.4.1-fpm
    container_name: php-fpm
    volumes:
      - ./php-fpm:/var/www/html #Path sans doutes a modifier
    networks:
      - camagru-network



  # Frontend React
  frontend:
    image: node:16
    container_name: Front
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - camagru-network
    depends_on:
      - backend

  # Base de données PostgreSQL
  postgres:
    image: postgres:13
    container_name: Postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - camagru-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service de mails MailHog pour tester l'envoi d'e-mails
  mailhog:
    image: mailhog/mailhog
    container_name: Mailhog
    ports:
      - "8025:8025"  # Interface web de MailHog
      - "1025:1025"  # SMTP pour l'envoi d'e-mails
    networks:
      - camagru-network

networks:
  camagru-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local